target("CyberCore")
    set_kind("shared")
    add_includedirs("include", {public=true})
    add_files("src/core/*.cpp", {public=true})
    add_files("src/platform/*.cpp", {public=true})
    add_files("src/log/*.cpp", {public=true})
    add_deps("EASTL", {public = true})
    add_deps("spdlog", {public=true})
    add_deps("CyberEvents", {public = true})
    add_defines("CYBER_API_EXPORT")
