includes("thirdparty/EASTL.lua")
includes("thirdparty/spdlog.lua")
includes("thirdparty/mimalloc.lua")
--includes("thirdparty/GLFW.lua")
includes("thirdparty/gainput.lua")
includes("thirdparty/DirectXMath.lua")
includes("thirdparty/DirectXShaderCompiler.lua")
includes("thirdparty/parallel_hashmap.lua")