target("CyberInputSystem")
    add_includedirs("include", {public=true})
    add_files("src/*.cpp")
    set_kind("shared")
    add_deps("CyberLog", {public=true})
    add_deps("Gainput", {public=true})
    add_deps("EASTL", {public=true})
    add_deps("mimalloc", {public = true})
    add_deps("Gainput", {public = true})
    add_deps("CyberRuntime", {public=true})