target("CyberRuntime")
    set_kind("shared")
    add_includedirs("include", {public=true})
    add_includedirs("include/graphics", {public=true})
    add_defines("CYBER_API_EXPORT")
    add_files("src/core/*.cpp")
    add_files("src/platform/*.cpp")
    add_files("src/graphics/interface/*.cpp")
    add_files("src/graphics/backend/d3d12/*.cpp")
    add_files("src/graphics/common/*.cpp")
    add_files("src/gui/*.cpp")
    add_files("src/graphics/resource/*.cpp")
    add_files("src/gameruntime/*.cpp")
    add_files("src/inputsystem/*.cpp")
    add_files("src/graphics/rendergraph/*.cpp")
    add_deps("EASTL", {public = true})
    add_deps("CyberLog", {public = true})
    add_deps("CyberEvents",{public=true})
    add_deps("mimalloc", {public = true})
    add_deps("Gainput", {public=true})
    add_deps("IMGUI", {public=true})
    set_configdir("$(projectdir)/Engine")
    add_configfiles("$(projectdir)/Engine/config.h.in")

