target("CyberRuntime")
    set_kind("shared")
    add_includedirs("include", {public=true})
    add_includedirs("include/graphics", {public=true})
    add_includedirs("include/tools", {public=true})
    add_includedirs("src/inputsystem", {public=true})
    add_defines("CYBER_API_EXPORT")
    add_files("src/graphics/interface/*.cpp")
    add_files("src/graphics/backend/d3d12/*.cpp")
    add_files("src/graphics/common/*.cpp")
    add_files("src/application/*.cpp")
    add_files("src/application/platform/windows/*.cpp")
    add_files("src/editor/*.cpp")
    add_files("src/component/*.cpp")
    add_files("src/gameruntime/*.cpp")
    add_files("src/renderer/*.cpp")
    add_files("src/graphics/resource/*.cpp")
    add_files("src/inputsystem/*.cpp")
    add_files("src/inputsystem/core/*.cpp")
    add_files("src/inputsystem/devices/*.cpp")
    add_files("src/inputsystem/platform/win32/*.cpp")
    add_files("src/graphics/rendergraph/*.cpp")
    --add_files("src/tools/texture_loader/*.cpp")
    add_deps("EASTL", {public = true})
    add_deps("CyberCore", {public = true})
    add_deps("CyberEvents",{public=true})
    add_deps("mimalloc", {public = true})
    add_deps("Gainput", {public=true})
    add_deps("IMGUI", {public=true})
    add_deps("stb", {public=true})
    add_deps("d3dx12", {public = true})
    set_configdir("$(projectdir)/Engine/modules/core/include/core")
    add_configfiles("$(projectdir)/Engine/modules/core/include/core/config.h.in")

