#pragma once
#include "cyber_rhi_config.h"
#include <stdint.h>

// enums
typedef enum ERHINvAPI_Status
{
    RHI_NVAPI_OK = 0,
    RHI_NVAPI_NONE = 1,
    RHI_NVAPI_ERROR = -1,
    RHI_NVAPI_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHINvAPI_Status;

typedef enum ERHIAGSReturenCode
{
    RHI_AGS_SUCCESS,                    ///< Successful function call
    RHI_AGS_FAILURE,                    ///< Failed to complete call for some unspecified reason
    RHI_AGS_INVALID_ARGS,               ///< Invalid arguments into the function
    RHI_AGS_OUT_OF_MEMORY,              ///< Out of memory when allocating space internally
    RHI_AGS_MISSING_D3D_DLL,            ///< Returned when a D3D dll fails to load
    RHI_AGS_LEGACY_DRIVER,              ///< Returned if a feature is not present in the installed driver
    RHI_AGS_NO_AMD_DRIVER_INSTALLED,    ///< Returned if the AMD GPU driver does not appear to be installed
    RHI_AGS_EXTENSION_NOT_SUPPORTED,    ///< Returned if the driver does not support the requested driver extension
    RHI_AGS_ADL_FAILURE,                ///< Failure in ADL (the AMD Display Library)
    RHI_AGS_DX_FAILURE,                 ///< Failure from DirectX runtime
    RHI_AGS_NONE,
    RHI_AGS_MAX_ENUN_BIT = 0x7FFFFFFF
} ERHIAGSReturenCode;

typedef enum ERHITextureDimension
{
    RHI_TEX_DIMENSION_1D,
    RHI_TEX_DIMENSION_2D,
    RHI_TEX_DIMENSION_2DMS,
    RHI_TEX_DIMENSION_3D,
    RHI_TEX_DIMENSION_CUBE,
    RHI_TEX_DIMENSION_1D_ARRAY,
    RHI_TEX_DIMENSION_2D_ARRAY,
    RHI_TEX_DIMENSION_2DMS_ARRAY,
    RHI_TEX_DIMENSION_CUBE_ARRAY,
    RHI_TEX_DIMENSION_COUNT,
    RHI_TEX_DIMENSION_UNDEFINED,
    RHI_TEX_DIMENSION_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHITextureDimension;

typedef enum ERHIPipelineType
{
    RHI_PIPELINE_TYPE_NONE = 0,
    RHI_PIPELINE_TYPE_COMPUTE,
    RHI_PIPELINE_TYPE_GRAPHICS,
    RHI_PIPELINE_TYPE_RAYTRACING,
    RHI_PIPELINE_TYPE_COUNT,
    RHI_PIPELINE_TYPE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIPipelineType;


typedef enum ERHIQueueType
{
    RHI_QUEUE_TYPE_GRAPHICS = 0,
    RHI_QUEUE_TYPE_COMPUTE = 1,
    RHI_QUEUE_TYPE_TRANSFER = 2,
    RHI_QUEUE_TYPE_COUNT,
    MAX_QUEUE_TYPE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIQueueType;

enum ERHIQueueFlag 
{
    RHI_QUEUE_FLAG_NONE = 0x0,
    RHI_QUEUE_FLAG_DISABLE_GPU_TIMEOUT = 0x1,
    RHI_QUEUE_FLAG_INIT_MICROPROFILE = 0x2,
    MAX_QUEUE_FLAG = 0xFFFFFFFF
};


enum ERHIIndirectArgumentType
{
    RHI_INDIRECT_ARG_INVALID,
    RHI_INDIRECT_DRAW,
    RHI_INDIRECT_DRAW_INDEX,
    RHI_INDIRECT_DISPATCH,
    RHI_INDIRECT_VERTEX_BUFFER,
    RHI_INDIRECT_INDEX_BUFFER,
    RHI_INDIRECT_CONSTANT,
    RHI_INDIRECT_CONSTANT_BUFFER_VIEW,     // only for dx
    RHI_INDIRECT_SHADER_RESOURCE_VIEW,     // only for dx
    RHI_INDIRECT_UNORDERED_ACCESS_VIEW,    // only for dx
    RHI_INDIRECT_COMMAND_BUFFER,            // metal ICB
    RHI_INDIRECT_COMMAND_BUFFER_RESET,      // metal ICB reset
    RHI_INDIRECT_COMMAND_BUFFER_OPTIMIZE    // metal ICB optimization
};
enum ERHIDescriptorType
{
    RHI_DESCRIPTOR_TYPE_UNDEFINED = 0,
    RHI_DESCRIPTOR_TYPE_SAMPLER = 0x01,
    // SRV Read only texture
    RHI_DESCRIPTOR_TYPE_TEXTURE = (RHI_DESCRIPTOR_TYPE_SAMPLER << 1),
    /// UAV Texture
    RHI_DESCRIPTOR_TYPE_RW_TEXTURE = (RHI_DESCRIPTOR_TYPE_TEXTURE << 1),
    // SRV Read only buffer
    RHI_DESCRIPTOR_TYPE_BUFFER = (RHI_DESCRIPTOR_TYPE_RW_TEXTURE << 1),
    RHI_DESCRIPTOR_TYPE_BUFFER_RAW = (RHI_DESCRIPTOR_TYPE_BUFFER | (RHI_DESCRIPTOR_TYPE_BUFFER << 1)),
    /// UAV Buffer
    RHI_DESCRIPTOR_TYPE_RW_BUFFER = (RHI_DESCRIPTOR_TYPE_BUFFER << 2),
    RHI_DESCRIPTOR_TYPE_RW_BUFFER_RAW = (RHI_DESCRIPTOR_TYPE_RW_BUFFER | (RHI_DESCRIPTOR_TYPE_RW_BUFFER << 1)),
    /// Uniform buffer
    RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER = (RHI_DESCRIPTOR_TYPE_RW_BUFFER << 2),
    /// Push constant / Root constant
    RHI_DESCRIPTOR_TYPE_ROOT_CONSTANT = (RHI_DESCRIPTOR_TYPE_UNIFORM_BUFFER << 1),
    /// IA
    RHI_DESCRIPTOR_TYPE_VERTEX_BUFFER = (RHI_DESCRIPTOR_TYPE_ROOT_CONSTANT << 1),
    RHI_DESCRIPTOR_TYPE_INDEX_BUFFER = (RHI_DESCRIPTOR_TYPE_VERTEX_BUFFER << 1),
    RHI_DESCRIPTOR_TYPE_INDIRECT_BUFFER = (RHI_DESCRIPTOR_TYPE_INDEX_BUFFER << 1),
    /// Cubemap SRV
    RHI_DESCRIPTOR_TYPE_TEXTURE_CUBE = (RHI_DESCRIPTOR_TYPE_TEXTURE | (RHI_DESCRIPTOR_TYPE_INDIRECT_BUFFER << 1)),
    /// RTV / DSV per mip slice
    RHI_DESCRIPTOR_TYPE_RENDER_TARGET_MIP_SLICES = (RHI_DESCRIPTOR_TYPE_INDIRECT_BUFFER << 2),
    /// RTV / DSV per array slice
    RHI_DESCRIPTOR_TYPE_RENDER_TARGET_ARRAY_SLICES = (RHI_DESCRIPTOR_TYPE_RENDER_TARGET_MIP_SLICES << 1),
    /// RTV / DSV per depth slice
    RHI_DESCRIPTOR_TYPE_RENDER_TARGET_DEPTH_SLICES = (RHI_DESCRIPTOR_TYPE_RENDER_TARGET_ARRAY_SLICES << 1),
    RHI_DESCRIPTOR_TYPE_RAY_TRACING = (RHI_DESCRIPTOR_TYPE_RENDER_TARGET_DEPTH_SLICES << 1),
    RHI_DESCRIPTOR_TYPE_INDIRECT_COMMAND_BUFFER = (RHI_DESCRIPTOR_TYPE_RAY_TRACING << 1),
#if defined(VULKAN)
    /// Subpass input (descriptor type only available in Vulkan)
    DESCRIPTOR_TYPE_INPUT_ATTACHMENT = (DESCRIPTOR_TYPE_INDIRECT_COMMAND_BUFFER << 1),
    DESCRIPTOR_TYPE_TEXEL_BUFFER = (DESCRIPTOR_TYPE_INPUT_ATTACHMENT << 1),
    DESCRIPTOR_TYPE_RW_TEXEL_BUFFER = (DESCRIPTOR_TYPE_TEXEL_BUFFER << 1),
    DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER = (DESCRIPTOR_TYPE_RW_TEXEL_BUFFER << 1),
    
    /// Khronos extension ray tracing
    DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE = (DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER << 1),
    DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_BUILD_INPUT = (DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE << 1),
    DESCRIPTOR_TYPE_SHADER_DEVICE_ADDRESS = (DESCRIPTOR_TYPE_ACCELERATION_STRUCTURE_BUILD_INPUT << 1),
    DESCRIPTOR_TYPE_SHADER_BINDING_TABLE = (DESCRIPTOR_TYPE_SHADER_DEVICE_ADDRESS << 1),
#endif
};
enum ERHITextureCreationFlag
{
    /// Default flag (Texture will use default allocation strategy decided by the api specific allocator)
    RHI_TCF_NONE = 0,
    /// Texture will allocate its own memory (COMMITTED resource)
    RHI_TCF_OWN_MEMORY_BIT = 0x01,
    /// Texture will be allocated in memory which can be shared among multiple processes
    RHI_TCF_EXPORT_BIT = 0x02,
    /// Texture will be allocated in memory which can be shared among multiple gpus
    RHI_TCF_EXPORT_ADAPTER_BIT = 0x04,
    /// Use on-tile memory to store this texture
    RHI_TCF_ON_TILE = 0x08,
    /// Prevent compression meta data from generating (XBox)
    RHI_TCF_NO_COMPRESSION = 0x10,
    /// Force 2D instead of automatically determining dimension based on width, height, depth
    RHI_TCF_FORCE_2D = 0x20,
    /// Force 3D instead of automatically determining dimension based on width, height, depth
    RHI_TCF_FORCE_3D = 0x40,
    /// Display target
    RHI_TCF_FORCE_ALLOW_DISPLAY_TARGET = 0x80,
    /// Create an sRGB texture.
    RHI_TCF_SRGB = 0x100,
    /// Create a normal map texture
    RHI_TCF_NORMAL_MAP = 0x200,
    /// Fragment mask
    RHI_TCF_FRAG_MASK = 0x400,
    RHI_TCF_USABLE_MAX = 0x40000,
    RHI_TCF_MAX_ENUM_BIT = 0x7FFFFFFF
};
typedef uint32_t RHITextureCreationFlag;
enum ERHITextureSampleCount
{
    RHI_SAMPLE_COUNT_1 = 1,
    RHI_SAMPLE_COUNT_2 = 2,
    RHI_SAMPLE_COUNT_4 = 4,
    RHI_SAMPLE_COUNT_8 = 8,
    RHI_SAMPLE_COUNT_16 = 16,
    RHI_SAMPLE_COUNT_COUNT = 5
};
enum ERHIFormat
{
    RHI_FORMAT_UNDEFINED = 0,
    RHI_FORMAT_R1_UNORM = 1,
    RHI_FORMAT_R2_UNORM = 2,   
    RHI_FORMAT_R4_UNORM = 3,
    RHI_FORMAT_R4G4_UNORM = 4,
    RHI_FORMAT_G4R4_UNORM = 5,
    RHI_FORMAT_A8_UNORM = 6,
    RHI_FORMAT_R8_UNORM = 7,
    RHI_FORMAT_R8_SNORM = 8,
    RHI_FORMAT_R8_UINT = 9,
    RHI_FORMAT_R8_SINT = 10,
    RHI_FORMAT_R8_SRGB = 11,
    RHI_FORMAT_B2G3R3_UNORM = 12,
    RHI_FORMAT_R4G4B4A4_UNORM = 13,
    RHI_FORMAT_R4G4B4X4_UNORM = 14,
    RHI_FORMAT_B4G4R4A4_UNORM = 15,
    RHI_FORMAT_B4G4R4X4_UNORM = 16,
    RHI_FORMAT_A4R4G4B4_UNORM = 17,
    RHI_FORMAT_X4R4G4B4_UNORM = 18,
    RHI_FORMAT_A4B4G4R4_UNORM = 19,
    RHI_FORMAT_X4B4G4R4_UNORM = 20,
    RHI_FORMAT_R5G6B5_UNORM = 21,
    RHI_FORMAT_B5G6R5_UNORM = 22,
    RHI_FORMAT_R5G5B5A1_UNORM = 23,
    RHI_FORMAT_B5G5R5A1_UNORM = 24,
    RHI_FORMAT_A1B5G5R5_UNORM = 25,
    RHI_FORMAT_A1R5G5B5_UNORM = 26,
    RHI_FORMAT_R5G5B5X1_UNORM = 27,
    RHI_FORMAT_B5G5R5X1_UNORM = 28,
    RHI_FORMAT_X1R5G5B5_UNORM = 29,
    RHI_FORMAT_X1B5G5R5_UNORM = 30,
    RHI_FORMAT_B2G3R3A8_UNORM = 31,
    RHI_FORMAT_R8G8_UNORM = 32,
    RHI_FORMAT_R8G8_SNORM = 33,
    RHI_FORMAT_G8R8_UNORM = 34,
    RHI_FORMAT_G8R8_SNORM = 35,
    RHI_FORMAT_R8G8_UINT = 36,
    RHI_FORMAT_R8G8_SINT = 37,
    RHI_FORMAT_R8G8_SRGB = 38,
    RHI_FORMAT_R16_UNORM = 39,
    RHI_FORMAT_R16_SNORM = 40,
    RHI_FORMAT_R16_UINT = 41,
    RHI_FORMAT_R16_SINT = 42,
    RHI_FORMAT_R16_SFLOAT = 43,
    RHI_FORMAT_R16_SBFLOAT = 44,
    RHI_FORMAT_R8G8B8_UNORM = 45,
    RHI_FORMAT_R8G8B8_SNORM = 46,
    RHI_FORMAT_R8G8B8_UINT = 47,
    RHI_FORMAT_R8G8B8_SINT = 48,
    RHI_FORMAT_R8G8B8_SRGB = 49,
    RHI_FORMAT_B8G8R8_UNORM = 50,
    RHI_FORMAT_B8G8R8_SNORM = 51,
    RHI_FORMAT_B8G8R8_UINT = 52,
    RHI_FORMAT_B8G8R8_SINT = 53,
    RHI_FORMAT_B8G8R8_SRGB = 54,
    RHI_FORMAT_R8G8B8A8_UNORM = 55,
    RHI_FORMAT_R8G8B8A8_SNORM = 56,
    RHI_FORMAT_R8G8B8A8_UINT = 57,
    RHI_FORMAT_R8G8B8A8_SINT = 58,
    RHI_FORMAT_R8G8B8A8_SRGB = 59,
    RHI_FORMAT_B8G8R8A8_UNORM = 60,
    RHI_FORMAT_B8G8R8A8_SNORM = 61,
    RHI_FORMAT_B8G8R8A8_UINT = 62,
    RHI_FORMAT_B8G8R8A8_SINT = 63,
    RHI_FORMAT_B8G8R8A8_SRGB = 64,
    RHI_FORMAT_R8G8B8X8_UNORM = 65,
    RHI_FORMAT_B8G8R8X8_UNORM = 66,
    RHI_FORMAT_R16G16_UNORM = 67,
    RHI_FORMAT_G16R16_UNORM = 68,
    RHI_FORMAT_R16G16_SNORM = 69,
    RHI_FORMAT_G16R16_SNORM = 70,
    RHI_FORMAT_R16G16_UINT = 71,
    RHI_FORMAT_R16G16_SINT = 72,
    RHI_FORMAT_R16G16_SFLOAT = 73,
    RHI_FORMAT_R16G16_SBFLOAT = 74,
    RHI_FORMAT_R32_UINT = 75,
    RHI_FORMAT_R32_SINT = 76,
    RHI_FORMAT_R32_SFLOAT = 77,
    RHI_FORMAT_A2R10G10B10_UNORM = 78,
    RHI_FORMAT_A2R10G10B10_UINT = 79,
    RHI_FORMAT_A2R10G10B10_SNORM = 80,
    RHI_FORMAT_A2R10G10B10_SINT = 81,
    RHI_FORMAT_A2B10G10R10_UNORM = 82,
    RHI_FORMAT_A2B10G10R10_UINT = 83,
    RHI_FORMAT_A2B10G10R10_SNORM = 84,
    RHI_FORMAT_A2B10G10R10_SINT = 85,
    RHI_FORMAT_R10G10B10A2_UNORM = 86,
    RHI_FORMAT_R10G10B10A2_UINT = 87,
    RHI_FORMAT_R10G10B10A2_SNORM = 88,
    RHI_FORMAT_R10G10B10A2_SINT = 89,
    RHI_FORMAT_B10G10R10A2_UNORM = 90,
    RHI_FORMAT_B10G10R10A2_UINT = 91,
    RHI_FORMAT_B10G10R10A2_SNORM = 92,
    RHI_FORMAT_B10G10R10A2_SINT = 93,
    RHI_FORMAT_B10G11R11_UFLOAT = 94,
    RHI_FORMAT_E5B9G9R9_UFLOAT = 95,
    RHI_FORMAT_R16G16B16_UNORM = 96,
    RHI_FORMAT_R16G16B16_SNORM = 97,
    RHI_FORMAT_R16G16B16_UINT = 98,
    RHI_FORMAT_R16G16B16_SINT = 99,
    RHI_FORMAT_R16G16B16_SFLOAT = 100,
    RHI_FORMAT_R16G16B16_SBFLOAT = 101,
    RHI_FORMAT_R16G16B16A16_UNORM = 102,
    RHI_FORMAT_R16G16B16A16_SNORM = 103,
    RHI_FORMAT_R16G16B16A16_UINT = 104,
    RHI_FORMAT_R16G16B16A16_SINT = 105,
    RHI_FORMAT_R16G16B16A16_SFLOAT = 106,
    RHI_FORMAT_R16G16B16A16_SBFLOAT = 107,
    RHI_FORMAT_R32G32_UINT = 108,
    RHI_FORMAT_R32G32_SINT = 109,
    RHI_FORMAT_R32G32_SFLOAT = 110,
    RHI_FORMAT_R32G32B32_UINT = 111,
    RHI_FORMAT_R32G32B32_SINT = 112,
    RHI_FORMAT_R32G32B32_SFLOAT = 113,
    RHI_FORMAT_R32G32B32A32_UINT = 114,
    RHI_FORMAT_R32G32B32A32_SINT = 115,
    RHI_FORMAT_R32G32B32A32_SFLOAT = 116,
    RHI_FORMAT_R64_UINT = 117,
    RHI_FORMAT_R64_SINT = 118,
    RHI_FORMAT_R64_SFLOAT = 119,
    RHI_FORMAT_R64G64_UINT = 120,
    RHI_FORMAT_R64G64_SINT = 121,
    RHI_FORMAT_R64G64_SFLOAT = 122,
    RHI_FORMAT_R64G64B64_UINT = 123,
    RHI_FORMAT_R64G64B64_SINT = 124,
    RHI_FORMAT_R64G64B64_SFLOAT = 125,
    RHI_FORMAT_R64G64B64A64_UINT = 126,
    RHI_FORMAT_R64G64B64A64_SINT = 127,
    RHI_FORMAT_R64G64B64A64_SFLOAT = 128,
    RHI_FORMAT_D16_UNORM = 129,
    RHI_FORMAT_X8_D24_UNORM = 130,
    RHI_FORMAT_D32_SFLOAT = 131,
    RHI_FORMAT_S8_UINT = 132,
    RHI_FORMAT_D16_UNORM_S8_UINT = 133,
    RHI_FORMAT_D24_UNORM_S8_UINT = 134,
    RHI_FORMAT_D32_SFLOAT_S8_UINT = 135,
    RHI_FORMAT_DXBC1_RGB_UNORM = 136,
    RHI_FORMAT_DXBC1_RGB_SRGB = 137,
    RHI_FORMAT_DXBC1_RGBA_UNORM = 138,
    RHI_FORMAT_DXBC1_RGBA_SRGB = 139,
    RHI_FORMAT_DXBC2_UNORM = 140,
    RHI_FORMAT_DXBC2_SRGB = 141,
    RHI_FORMAT_DXBC3_UNORM = 142,
    RHI_FORMAT_DXBC3_SRGB = 143,
    RHI_FORMAT_DXBC4_UNORM = 144,
    RHI_FORMAT_DXBC4_SNORM = 145,
    RHI_FORMAT_DXBC5_UNORM = 146,
    RHI_FORMAT_DXBC5_SNORM = 147,
    RHI_FORMAT_DXBC6H_UFLOAT = 148,
    RHI_FORMAT_DXBC6H_SFLOAT = 149,
    RHI_FORMAT_DXBC7_UNORM = 150,
    RHI_FORMAT_DXBC7_SRGB = 151,
    RHI_FORMAT_PVRTC1_2BPP_UNORM = 152,
    RHI_FORMAT_PVRTC1_4BPP_UNORM = 153,
    RHI_FORMAT_PVRTC2_2BPP_UNORM = 154,
    RHI_FORMAT_PVRTC2_4BPP_UNORM = 155,
    RHI_FORMAT_PVRTC1_2BPP_SRGB = 156,
    RHI_FORMAT_PVRTC1_4BPP_SRGB = 157,
    RHI_FORMAT_PVRTC2_2BPP_SRGB = 158,
    RHI_FORMAT_PVRTC2_4BPP_SRGB = 159,
    RHI_FORMAT_ETC2_R8G8B8_UNORM = 160,
    RHI_FORMAT_ETC2_R8G8B8_SRGB = 161,
    RHI_FORMAT_ETC2_R8G8B8A1_UNORM = 162,
    RHI_FORMAT_ETC2_R8G8B8A1_SRGB = 163,
    RHI_FORMAT_ETC2_R8G8B8A8_UNORM = 164,
    RHI_FORMAT_ETC2_R8G8B8A8_SRGB = 165,
    RHI_FORMAT_ETC2_EAC_R11_UNORM = 166,
    RHI_FORMAT_ETC2_EAC_R11_SNORM = 167,
    RHI_FORMAT_ETC2_EAC_R11G11_UNORM = 168,
    RHI_FORMAT_ETC2_EAC_R11G11_SNORM = 169,
    RHI_FORMAT_ASTC_4x4_UNORM = 170,
    RHI_FORMAT_ASTC_4x4_SRGB = 171,
    RHI_FORMAT_ASTC_5x4_UNORM = 172,
    RHI_FORMAT_ASTC_5x4_SRGB = 173,
    RHI_FORMAT_ASTC_5x5_UNORM = 174,
    RHI_FORMAT_ASTC_5x5_SRGB = 175,
    RHI_FORMAT_ASTC_6x5_UNORM = 176,
    RHI_FORMAT_ASTC_6x5_SRGB = 177,
    RHI_FORMAT_ASTC_6x6_UNORM = 178,
    RHI_FORMAT_ASTC_6x6_SRGB = 179,
    RHI_FORMAT_ASTC_8x5_UNORM = 180,
    RHI_FORMAT_ASTC_8x5_SRGB = 181,
    RHI_FORMAT_ASTC_8x6_UNORM = 182,
    RHI_FORMAT_ASTC_8x6_SRGB = 183,
    RHI_FORMAT_ASTC_8x8_UNORM = 184,
    RHI_FORMAT_ASTC_8x8_SRGB = 185,
    RHI_FORMAT_ASTC_10x5_UNORM = 186,
    RHI_FORMAT_ASTC_10x5_SRGB = 187,
    RHI_FORMAT_ASTC_10x6_UNORM = 188,
    RHI_FORMAT_ASTC_10x6_SRGB = 189,
    RHI_FORMAT_ASTC_10x8_UNORM = 190,
    RHI_FORMAT_ASTC_10x8_SRGB = 191,
    RHI_FORMAT_ASTC_10x10_UNORM = 192,
    RHI_FORMAT_ASTC_10x10_SRGB = 193,
    RHI_FORMAT_ASTC_12x10_UNORM = 194,
    RHI_FORMAT_ASTC_12x10_SRGB = 195,
    RHI_FORMAT_ASTC_12x12_UNORM = 196,
    RHI_FORMAT_ASTC_12x12_SRGB = 197,
    RHI_FORMAT_CLUT_P4 = 198,
    RHI_FORMAT_CLUT_P4A4 = 199,
    RHI_FORMAT_CLUT_P8 = 200,
    RHI_FORMAT_CLUT_P8A8 = 201,
    RHI_FORMAT_R4G4B4A4_UNORM_PACK16 = 202,
    RHI_FORMAT_B4G4R4A4_UNORM_PACK16 = 203,
    RHI_FORMAT_R5G6B5_UNORM_PACK16 = 204,
    RHI_FORMAT_B5G6R5_UNORM_PACK16 = 205,
    RHI_FORMAT_R5G5B5A1_UNORM_PACK16 = 206,
    RHI_FORMAT_B5G5R5A1_UNORM_PACK16 = 207,
    RHI_FORMAT_A1R5G5B5_UNORM_PACK16 = 208,
    RHI_FORMAT_G16B16G16R16_422_UNORM = 209,
    RHI_FORMAT_B16G16R16G16_422_UNORM = 210,
    RHI_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16 = 211,
    RHI_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16 = 212,
    RHI_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16 = 213,
    RHI_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16 = 214,
    RHI_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16 = 215,
    RHI_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16 = 216,
    RHI_FORMAT_G8B8G8R8_422_UNORM = 217,
    RHI_FORMAT_B8G8R8G8_422_UNORM = 218,
    RHI_FORMAT_G8_B8_R8_3PLANE_420_UNORM = 219,
    RHI_FORMAT_G8_B8R8_2PLANE_420_UNORM = 220,
    RHI_FORMAT_G8_B8_R8_3PLANE_422_UNORM = 221,
    RHI_FORMAT_G8_B8R8_2PLANE_422_UNORM = 222,
    RHI_FORMAT_G8_B8_R8_3PLANE_444_UNORM = 223,
    RHI_FORMAT_G10X6_B10X6_R10X6_3PLANE_420_UNORM_3PACK16 = 224,
    RHI_FORMAT_G10X6_B10X6_R10X6_3PLANE_422_UNORM_3PACK16 = 225,
    RHI_FORMAT_G10X6_B10X6_R10X6_3PLANE_444_UNORM_3PACK16 = 226,
    RHI_FORMAT_G10X6_B10X6R10X6_2PLANE_420_UNORM_3PACK16 = 227,
    RHI_FORMAT_G10X6_B10X6R10X6_2PLANE_422_UNORM_3PACK16 = 228,
    RHI_FORMAT_G12X4_B12X4_R12X4_3PLANE_420_UNORM_3PACK16 = 229,
    RHI_FORMAT_G12X4_B12X4_R12X4_3PLANE_422_UNORM_3PACK16 = 230,
    RHI_FORMAT_G12X4_B12X4_R12X4_3PLANE_444_UNORM_3PACK16 = 231,
    RHI_FORMAT_G12X4_B12X4R12X4_2PLANE_420_UNORM_3PACK16 = 232,
    RHI_FORMAT_G12X4_B12X4R12X4_2PLANE_422_UNORM_3PACK16 = 233,
    RHI_FORMAT_G16_B16_R16_3PLANE_420_UNORM = 234,
    RHI_FORMAT_G16_B16_R16_3PLANE_422_UNORM = 235,
    RHI_FORMAT_G16_B16_R16_3PLANE_444_UNORM = 236,
    RHI_FORMAT_G16_B16R16_2PLANE_420_UNORM = 237,
    RHI_FORMAT_G16_B16R16_2PLANE_422_UNORM = 238,
    RHI_FORMAT_COUNT = RHI_FORMAT_G16_B16R16_2PLANE_422_UNORM + 1,
    RHI_FORMAT_MAX_ENUM_BIT = 0x7FFFFFFF
};

static FORCEINLINE uint32_t FormatUtil_BitSizeOfBlock(ERHIFormat fmt)
{
    switch (fmt) 
    {
        case RHI_FORMAT_UNDEFINED: return 0;
        case RHI_FORMAT_R1_UNORM: return 8;
        case RHI_FORMAT_R2_UNORM: return 8;
        case RHI_FORMAT_R4_UNORM: return 8;
        case RHI_FORMAT_R4G4_UNORM: return 8;
        case RHI_FORMAT_G4R4_UNORM: return 8;
        case RHI_FORMAT_A8_UNORM: return 8;
        case RHI_FORMAT_R8_UNORM: return 8;
        case RHI_FORMAT_R8_SNORM: return 8;
        case RHI_FORMAT_R8_UINT: return 8;
        case RHI_FORMAT_R8_SINT: return 8;
        case RHI_FORMAT_R8_SRGB: return 8;
        case RHI_FORMAT_B2G3R3_UNORM: return 8;
        case RHI_FORMAT_R4G4B4A4_UNORM: return 16;
        case RHI_FORMAT_R4G4B4X4_UNORM: return 16;
        case RHI_FORMAT_B4G4R4A4_UNORM: return 16;
        case RHI_FORMAT_B4G4R4X4_UNORM: return 16;
        case RHI_FORMAT_A4R4G4B4_UNORM: return 16;
        case RHI_FORMAT_X4R4G4B4_UNORM: return 16;
        case RHI_FORMAT_A4B4G4R4_UNORM: return 16;
        case RHI_FORMAT_X4B4G4R4_UNORM: return 16;
        case RHI_FORMAT_R5G6B5_UNORM: return 16;
        case RHI_FORMAT_B5G6R5_UNORM: return 16;
        case RHI_FORMAT_R5G5B5A1_UNORM: return 16;
        case RHI_FORMAT_B5G5R5A1_UNORM: return 16;
        case RHI_FORMAT_A1B5G5R5_UNORM: return 16;
        case RHI_FORMAT_A1R5G5B5_UNORM: return 16;
        case RHI_FORMAT_R5G5B5X1_UNORM: return 16;
        case RHI_FORMAT_B5G5R5X1_UNORM: return 16;
        case RHI_FORMAT_X1R5G5B5_UNORM: return 16;
        case RHI_FORMAT_X1B5G5R5_UNORM: return 16;
        case RHI_FORMAT_B2G3R3A8_UNORM: return 16;
        case RHI_FORMAT_R8G8_UNORM: return 16;
        case RHI_FORMAT_R8G8_SNORM: return 16;
        case RHI_FORMAT_G8R8_UNORM: return 16;
        case RHI_FORMAT_G8R8_SNORM: return 16;
        case RHI_FORMAT_R8G8_UINT: return 16;
        case RHI_FORMAT_R8G8_SINT: return 16;
        case RHI_FORMAT_R8G8_SRGB: return 16;
        case RHI_FORMAT_R16_UNORM: return 16;
        case RHI_FORMAT_R16_SNORM: return 16;
        case RHI_FORMAT_R16_UINT: return 16;
        case RHI_FORMAT_R16_SINT: return 16;
        case RHI_FORMAT_R16_SFLOAT: return 16;
        case RHI_FORMAT_R16_SBFLOAT: return 16;
        case RHI_FORMAT_R8G8B8_UNORM: return 24;
        case RHI_FORMAT_R8G8B8_SNORM: return 24;
        case RHI_FORMAT_R8G8B8_UINT: return 24;
        case RHI_FORMAT_R8G8B8_SINT: return 24;
        case RHI_FORMAT_R8G8B8_SRGB: return 24;
        case RHI_FORMAT_B8G8R8_UNORM: return 24;
        case RHI_FORMAT_B8G8R8_SNORM: return 24;
        case RHI_FORMAT_B8G8R8_UINT: return 24;
        case RHI_FORMAT_B8G8R8_SINT: return 24;
        case RHI_FORMAT_B8G8R8_SRGB: return 24;
        case RHI_FORMAT_R8G8B8A8_UNORM: return 32;
        case RHI_FORMAT_R8G8B8A8_SNORM: return 32;
        case RHI_FORMAT_R8G8B8A8_UINT: return 32;
        case RHI_FORMAT_R8G8B8A8_SINT: return 32;
        case RHI_FORMAT_R8G8B8A8_SRGB: return 32;
        case RHI_FORMAT_B8G8R8A8_UNORM: return 32;
        case RHI_FORMAT_B8G8R8A8_SNORM: return 32;
        case RHI_FORMAT_B8G8R8A8_UINT: return 32;
        case RHI_FORMAT_B8G8R8A8_SINT: return 32;
        case RHI_FORMAT_B8G8R8A8_SRGB: return 32;
        case RHI_FORMAT_R8G8B8X8_UNORM: return 32;
        case RHI_FORMAT_B8G8R8X8_UNORM: return 32;
        case RHI_FORMAT_R16G16_UNORM: return 32;
        case RHI_FORMAT_G16R16_UNORM: return 32;
        case RHI_FORMAT_R16G16_SNORM: return 32;
        case RHI_FORMAT_G16R16_SNORM: return 32;
        case RHI_FORMAT_R16G16_UINT: return 32;
        case RHI_FORMAT_R16G16_SINT: return 32;
        case RHI_FORMAT_R16G16_SFLOAT: return 32;
        case RHI_FORMAT_R16G16_SBFLOAT: return 32;
        case RHI_FORMAT_R32_UINT: return 32;
        case RHI_FORMAT_R32_SINT: return 32;
        case RHI_FORMAT_R32_SFLOAT: return 32;
        case RHI_FORMAT_A2R10G10B10_UNORM: return 32;
        case RHI_FORMAT_A2R10G10B10_UINT: return 32;
        case RHI_FORMAT_A2R10G10B10_SNORM: return 32;
        case RHI_FORMAT_A2R10G10B10_SINT: return 32;
        case RHI_FORMAT_A2B10G10R10_UNORM: return 32;
        case RHI_FORMAT_A2B10G10R10_UINT: return 32;
        case RHI_FORMAT_A2B10G10R10_SNORM: return 32;
        case RHI_FORMAT_A2B10G10R10_SINT: return 32;
        case RHI_FORMAT_R10G10B10A2_UNORM: return 32;
        case RHI_FORMAT_R10G10B10A2_UINT: return 32;
        case RHI_FORMAT_R10G10B10A2_SNORM: return 32;
        case RHI_FORMAT_R10G10B10A2_SINT: return 32;
        case RHI_FORMAT_B10G10R10A2_UNORM: return 32;
        case RHI_FORMAT_B10G10R10A2_UINT: return 32;
        case RHI_FORMAT_B10G10R10A2_SNORM: return 32;
        case RHI_FORMAT_B10G10R10A2_SINT: return 32;
        case RHI_FORMAT_B10G11R11_UFLOAT: return 32;
        case RHI_FORMAT_E5B9G9R9_UFLOAT: return 32;
        case RHI_FORMAT_R16G16B16_UNORM: return 48;
        case RHI_FORMAT_R16G16B16_SNORM: return 48;
        case RHI_FORMAT_R16G16B16_UINT: return 48;
        case RHI_FORMAT_R16G16B16_SINT: return 48;
        case RHI_FORMAT_R16G16B16_SFLOAT: return 48;
        case RHI_FORMAT_R16G16B16_SBFLOAT: return 48;
        case RHI_FORMAT_R16G16B16A16_UNORM: return 64;
        case RHI_FORMAT_R16G16B16A16_SNORM: return 64;
        case RHI_FORMAT_R16G16B16A16_UINT: return 64;
        case RHI_FORMAT_R16G16B16A16_SINT: return 64;
        case RHI_FORMAT_R16G16B16A16_SFLOAT: return 64;
        case RHI_FORMAT_R16G16B16A16_SBFLOAT: return 64;
        case RHI_FORMAT_R32G32_UINT: return 64;
        case RHI_FORMAT_R32G32_SINT: return 64;
        case RHI_FORMAT_R32G32_SFLOAT: return 64;
        case RHI_FORMAT_R32G32B32_UINT: return 96;
        case RHI_FORMAT_R32G32B32_SINT: return 96;
        case RHI_FORMAT_R32G32B32_SFLOAT: return 96;
        case RHI_FORMAT_R32G32B32A32_UINT: return 128;
        case RHI_FORMAT_R32G32B32A32_SINT: return 128;
        case RHI_FORMAT_R32G32B32A32_SFLOAT: return 128;
        case RHI_FORMAT_R64_UINT: return 64;
        case RHI_FORMAT_R64_SINT: return 64;
        case RHI_FORMAT_R64_SFLOAT: return 64;
        case RHI_FORMAT_R64G64_UINT: return 128;
        case RHI_FORMAT_R64G64_SINT: return 128;
        case RHI_FORMAT_R64G64_SFLOAT: return 128;
        case RHI_FORMAT_R64G64B64_UINT: return 192;
        case RHI_FORMAT_R64G64B64_SINT: return 192;
        case RHI_FORMAT_R64G64B64_SFLOAT: return 192;
        case RHI_FORMAT_R64G64B64A64_UINT: return 256;
        case RHI_FORMAT_R64G64B64A64_SINT: return 256;
        case RHI_FORMAT_R64G64B64A64_SFLOAT: return 256;
        case RHI_FORMAT_D16_UNORM: return 16;
        case RHI_FORMAT_X8_D24_UNORM: return 32;
        case RHI_FORMAT_D32_SFLOAT: return 32;
        case RHI_FORMAT_S8_UINT: return 8;
        case RHI_FORMAT_D16_UNORM_S8_UINT: return 24;
        case RHI_FORMAT_D24_UNORM_S8_UINT: return 32;
        case RHI_FORMAT_D32_SFLOAT_S8_UINT: return 40;
        case RHI_FORMAT_DXBC1_RGB_UNORM: return 64;
        case RHI_FORMAT_DXBC1_RGB_SRGB: return 64;
        case RHI_FORMAT_DXBC1_RGBA_UNORM: return 64;
        case RHI_FORMAT_DXBC1_RGBA_SRGB: return 64;
        case RHI_FORMAT_DXBC2_UNORM: return 128;
        case RHI_FORMAT_DXBC2_SRGB: return 128;
        case RHI_FORMAT_DXBC3_UNORM: return 128;
        case RHI_FORMAT_DXBC3_SRGB: return 128;
        case RHI_FORMAT_DXBC4_UNORM: return 64;
        case RHI_FORMAT_DXBC4_SNORM: return 64;
        case RHI_FORMAT_DXBC5_UNORM: return 128;
        case RHI_FORMAT_DXBC5_SNORM: return 128;
        case RHI_FORMAT_DXBC6H_UFLOAT: return 128;
        case RHI_FORMAT_DXBC6H_SFLOAT: return 128;
        case RHI_FORMAT_DXBC7_UNORM: return 128;
        case RHI_FORMAT_DXBC7_SRGB: return 128;
        case RHI_FORMAT_PVRTC1_2BPP_UNORM: return 64;
        case RHI_FORMAT_PVRTC1_4BPP_UNORM: return 64;
        case RHI_FORMAT_PVRTC2_2BPP_UNORM: return 64;
        case RHI_FORMAT_PVRTC2_4BPP_UNORM: return 64;
        case RHI_FORMAT_PVRTC1_2BPP_SRGB: return 64;
        case RHI_FORMAT_PVRTC1_4BPP_SRGB: return 64;
        case RHI_FORMAT_PVRTC2_2BPP_SRGB: return 64;
        case RHI_FORMAT_PVRTC2_4BPP_SRGB: return 64;
        case RHI_FORMAT_ETC2_R8G8B8_UNORM: return 64;
        case RHI_FORMAT_ETC2_R8G8B8_SRGB: return 64;
        case RHI_FORMAT_ETC2_R8G8B8A1_UNORM: return 64;
        case RHI_FORMAT_ETC2_R8G8B8A1_SRGB: return 64;
        case RHI_FORMAT_ETC2_R8G8B8A8_UNORM: return 64;
        case RHI_FORMAT_ETC2_R8G8B8A8_SRGB: return 64;
        case RHI_FORMAT_ETC2_EAC_R11_UNORM: return 64;
        case RHI_FORMAT_ETC2_EAC_R11_SNORM: return 64;
        case RHI_FORMAT_ETC2_EAC_R11G11_UNORM: return 64;
        case RHI_FORMAT_ETC2_EAC_R11G11_SNORM: return 64;
        case RHI_FORMAT_ASTC_4x4_UNORM: return 128;
        case RHI_FORMAT_ASTC_4x4_SRGB: return 128;
        case RHI_FORMAT_ASTC_5x4_UNORM: return 128;
        case RHI_FORMAT_ASTC_5x4_SRGB: return 128;
        case RHI_FORMAT_ASTC_5x5_UNORM: return 128;
        case RHI_FORMAT_ASTC_5x5_SRGB: return 128;
        case RHI_FORMAT_ASTC_6x5_UNORM: return 128;
        case RHI_FORMAT_ASTC_6x5_SRGB: return 128;
        case RHI_FORMAT_ASTC_6x6_UNORM: return 128;
        case RHI_FORMAT_ASTC_6x6_SRGB: return 128;
        case RHI_FORMAT_ASTC_8x5_UNORM: return 128;
        case RHI_FORMAT_ASTC_8x5_SRGB: return 128;
        case RHI_FORMAT_ASTC_8x6_UNORM: return 128;
        case RHI_FORMAT_ASTC_8x6_SRGB: return 128;
        case RHI_FORMAT_ASTC_8x8_UNORM: return 128;
        case RHI_FORMAT_ASTC_8x8_SRGB: return 128;
        case RHI_FORMAT_ASTC_10x5_UNORM: return 128;
        case RHI_FORMAT_ASTC_10x5_SRGB: return 128;
        case RHI_FORMAT_ASTC_10x6_UNORM: return 128;
        case RHI_FORMAT_ASTC_10x6_SRGB: return 128;
        case RHI_FORMAT_ASTC_10x8_UNORM: return 128;
        case RHI_FORMAT_ASTC_10x8_SRGB: return 128;
        case RHI_FORMAT_ASTC_10x10_UNORM: return 128;
        case RHI_FORMAT_ASTC_10x10_SRGB: return 128;
        case RHI_FORMAT_ASTC_12x10_UNORM: return 128;
        case RHI_FORMAT_ASTC_12x10_SRGB: return 128;
        case RHI_FORMAT_ASTC_12x12_UNORM: return 128;
        case RHI_FORMAT_ASTC_12x12_SRGB: return 128;
        case RHI_FORMAT_CLUT_P4: return 8;
        case RHI_FORMAT_CLUT_P4A4: return 8;
        case RHI_FORMAT_CLUT_P8: return 8;
        case RHI_FORMAT_CLUT_P8A8: return 16;
        case RHI_FORMAT_G16B16G16R16_422_UNORM: return 8;
        case RHI_FORMAT_B16G16R16G16_422_UNORM: return 8;
        case RHI_FORMAT_R12X4G12X4B12X4A12X4_UNORM_4PACK16: return 8;
        case RHI_FORMAT_G12X4B12X4G12X4R12X4_422_UNORM_4PACK16: return 8;
        case RHI_FORMAT_B12X4G12X4R12X4G12X4_422_UNORM_4PACK16: return 8;
        case RHI_FORMAT_R10X6G10X6B10X6A10X6_UNORM_4PACK16: return 8;
        case RHI_FORMAT_G10X6B10X6G10X6R10X6_422_UNORM_4PACK16: return 8;
        case RHI_FORMAT_B10X6G10X6R10X6G10X6_422_UNORM_4PACK16: return 8;
        case RHI_FORMAT_G8B8G8R8_422_UNORM: return 4;
        case RHI_FORMAT_B8G8R8G8_422_UNORM: return 4;
        default: return 32;
    }
}

static FORCEINLINE bool FormatUtil_IsDepthStencilFormat(ERHIFormat const fmt)
{
    switch (fmt)
    {
        case RHI_FORMAT_D24_UNORM_S8_UINT:
        case RHI_FORMAT_D32_SFLOAT_S8_UINT:
        case RHI_FORMAT_D32_SFLOAT:
        case RHI_FORMAT_X8_D24_UNORM:
        case RHI_FORMAT_D16_UNORM:
        case RHI_FORMAT_D16_UNORM_S8_UINT:
            return true;
        default:
            return false;
    }
}

typedef enum ERHIChannelBit
{
    RHI_CHANNEL_INVALID = 0,
    RHI_CHANNEL_R = 0x1,
    RHI_CHANNEL_G = 0x2,
    RHI_CHANNEL_B = 0x4,
    RHI_CHANNEL_A = 0x8,
    RHI_CHANNEL_RG = RHI_CHANNEL_R | RHI_CHANNEL_G,
    RHI_CHANNEL_RGB = RHI_CHANNEL_R | RHI_CHANNEL_G | RHI_CHANNEL_B,
    RHI_CHANNEL_RGBA = RHI_CHANNEL_R | RHI_CHANNEL_G | RHI_CHANNEL_B | RHI_CHANNEL_A,
    RHI_CHANNEL_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIChannelBit;

typedef enum ERHISlotMaskBit
{
    RHI_SLOT_0 = 0x1,
    RHI_SLOT_1 = 0x2,
    RHI_SLOT_2 = 0x4,
    RHI_SLOT_3 = 0x8,
    RHI_SLOT_4 = 0x10,
    RHI_SLOT_5 = 0x20,
    RHI_SLOT_6 = 0x40,
    RHI_SLOT_7 = 0x80,
} ERHISlotMaskBit;

enum ERHIResourceState
{
    RHI_RESOURCE_STATE_UNDEFINED = 0,
    RHI_RESOURCE_STATE_VERTEX_AND_CONSTANT_BUFFER = 0x1,
    RHI_RESOURCE_STATE_INDEX_BUFFER = 0x2,
    RHI_RESOURCE_STATE_RENDER_TARGET = 0x4,
    RHI_RESOURCE_STATE_UNORDERED_ACCESS = 0x8,
    RHI_RESOURCE_STATE_DEPTH_WRITE = 0x10,
    RHI_RESOURCE_STATE_DEPTH_READ = 0x20,
    RHI_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE = 0x40,
    RHI_RESOURCE_STATE_PIXEL_SHADER_RESOURCE = 0x80,
    RHI_RESOURCE_STATE_SHADER_RESOURCE = 0x40 | 0x80,
    RHI_RESOURCE_STATE_STREAM_OUT = 0x100,
    RHI_RESOURCE_STATE_INDIRECT_ARGUMENT = 0x200,
    RHI_RESOURCE_STATE_COPY_DEST = 0x400,
    RHI_RESOURCE_STATE_COPY_SOURCE = 0x800,
    RHI_RESOURCE_STATE_GENERIC_READ = (((((0x1 | 0x2) | 0x40) | 0x80) | 0x200) | 0x800),
    RHI_RESOURCE_STATE_PRESENT = 0x1000,
    RHI_RESOURCE_STATE_COMMON = 0x2000,
    RHI_RESOURCE_STATE_RAYTRACING_ACCELERATION_STRUCTURE = 0x4000,
    RHI_RESOURCE_STATE_SHADING_RATE_SOURCE = 0x8000,
};
typedef uint32_t RHIResourceState;
enum ERHIResourceMemoryUsage
{
    /// No intended memory usage specified.
    RHI_RESOURCE_MEMORY_USAGE_UNKNOWN = 0,
    /// Memory will be used on device only, no need to be mapped on host.
    RHI_RESOURCE_MEMORY_USAGE_GPU_ONLY = 1,
    /// Memory will be mapped on host. Could be used for transfer to device.
    RHI_RESOURCE_MEMORY_USAGE_CPU_ONLY = 2,
    /// Memory will be used for frequent (dynamic) updates from host and reads on device.
    RHI_RESOURCE_MEMORY_USAGE_CPU_TO_GPU = 3,
    /// Memory will be used for writing on device and readback on host.
    RHI_RESOURCE_MEMORY_USAGE_GPU_TO_CPU = 4,
    RHI_RESOURCE_MEMORY_USAGE_COUNT,
    RHI_RESOURCE_MEMORY_USAGE_MAX_ENUM = 0x7FFFFFFF
};
enum ERHIBufferCreationFlags
{
    /// Default flag (Buffer will use aliased memory, buffer will not be cpu accessible until mapBuffer is called)
    RHI_BCF_NONE = 0x01,
    /// Buffer will allocate its own memory (COMMITTED resource)
    RHI_BCF_OWN_MEMORY_BIT = 0x02,
    /// Buffer will be persistently mapped
    RHI_BCF_PERSISTENT_MAP_BIT = 0x04,
    /// Use ESRAM to store this buffer
    RHI_BCF_ESRAM = 0x08,
    /// Flag to specify not to allocate descriptors for the resource
    RHI_BCF_NO_DESCRIPTOR_VIEW_CREATION = 0x10,
#ifdef VULKAN
    /* Memory Host Flags */
    RHI_BCF_HOST_VISIBLE = 0x100,
    RHI_BCF_HOST_COHERENT = 0x200,
#endif
};
typedef uint32_t RHIBufferCreationFlags;
typedef enum ERHIScanlineOrdering
{
    RHI_SCANLINE_ORDER_UNSPECIFIED = 0,
    RHI_SCANLINE_ORDER_PROGRESSIVE = 1,
    RHI_SCANLINE_ORDER_UPPER_FIELD_FIRST = 2,
    RHI_SCANLINE_ORDER_LOWER_FIELD_FIRST = 3,
} ERHIScanlineOrdering;


typedef enum ERHIFenceStatus
{
    RHI_FENCE_STATUS_COMPLETE = 0,
    RHI_FENCE_STATUS_INCOMPLETE,
    RHI_FENCE_STATUS_NOTSUBMITTED,
    RHI_FENCE_STATUS_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIFenceStatus;

typedef enum ERHIQueryType
{
    RHI_QUERY_TYPE_TIMESTAMP = 0,
    RHI_QUERY_TYPE_PIPELINE_STATISTICS,
    RHI_QUERY_TYPE_OCCLUSION,
    RHI_QUERY_TYPE_COUNT,
    RHI_QUERY_TYPE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIQueryType;

typedef enum ERHIResourceType
{
    RHI_RESOURCE_TYPE_NONE = 0,
    RHI_RESOURCE_TYPE_SAMPLER = 0x00000001,
    /// SRV Read only texture
    RHI_RESOURCE_TYPE_TEXTURE = (RHI_RESOURCE_TYPE_SAMPLER << 1),
    /// RTV Texture
    RHI_RESOURCE_TYPE_RENDER_TARGET = (RHI_RESOURCE_TYPE_TEXTURE << 1),
    /// DSV Texture
    RHI_RESOURCE_TYPE_DEPTH_STENCIL = (RHI_RESOURCE_TYPE_RENDER_TARGET << 1),
    /// UAV Texture
    RHI_RESOURCE_TYPE_RW_TEXTURE = (RHI_RESOURCE_TYPE_DEPTH_STENCIL << 1),
    /// SRV Read only buffer
    RHI_RESOURCE_TYPE_BUFFER = (RHI_RESOURCE_TYPE_RW_TEXTURE << 1),
    RHI_RESOURCE_TYPE_BUFFER_RAW = (RHI_RESOURCE_TYPE_BUFFER | (RHI_RESOURCE_TYPE_BUFFER << 1)),
    /// UAV Buffer
    RHI_RESOURCE_TYPE_RW_BUFFER = (RHI_RESOURCE_TYPE_BUFFER << 2),
    RHI_RESOURCE_TYPE_RW_BUFFER_RAW = (RHI_RESOURCE_TYPE_RW_BUFFER | (RHI_RESOURCE_TYPE_RW_BUFFER << 1)),
    /// CBV Uniform buffer
    RHI_RESOURCE_TYPE_UNIFORM_BUFFER = (RHI_RESOURCE_TYPE_RW_BUFFER << 2),
    /// Push constant / Root constant
    RHI_RESOURCE_TYPE_PUSH_CONTANT = (RHI_RESOURCE_TYPE_UNIFORM_BUFFER << 1),
    /// IA
    RHI_RESOURCE_TYPE_VERTEX_BUFFER = (RHI_RESOURCE_TYPE_PUSH_CONTANT << 1),
    RHI_RESOURCE_TYPE_INDEX_BUFFER = (RHI_RESOURCE_TYPE_VERTEX_BUFFER << 1),
    RHI_RESOURCE_TYPE_INDIRECT_BUFFER = (RHI_RESOURCE_TYPE_INDEX_BUFFER << 1),
    /// Cubemap SRV
    RHI_RESOURCE_TYPE_TEXTURE_CUBE = (RHI_RESOURCE_TYPE_INDIRECT_BUFFER << 1),
    /// RTV / DSV per mip slice
    RHI_RESOURCE_TYPE_RENDER_TARGET_MIP_SLICES = (RHI_RESOURCE_TYPE_TEXTURE_CUBE << 1),
    /// RTV / DSV per array slice
    RHI_RESOURCE_TYPE_RENDER_TARGET_ARRAY_SLICES = (RHI_RESOURCE_TYPE_RENDER_TARGET_MIP_SLICES << 1),
    /// RTV / DSV per depth slice
    RHI_RESOURCE_TYPE_RENDER_TARGET_DEPTH_SLICES = (RHI_RESOURCE_TYPE_RENDER_TARGET_ARRAY_SLICES << 1),
    RHI_RESOURCE_TYPE_RAY_TRACING = (RHI_RESOURCE_TYPE_RENDER_TARGET_DEPTH_SLICES << 1),
#if defined (RHI_USE_VULKAN)
    /// Subpass input (descriptor type only available in Vulkan)
    RHI_RESOURCE_TYPE_INPUT_ATTACHMENT = (RHI_RESOURCE_TYPE_RAY_TRACING << 1),
    RHI_RESOURCE_TYPE_TEXEL_BUFFER = (RHI_RESOURCE_TYPE_INPUT_ATTACHMENT << 1),
    RHI_RESOURCE_TYPE_RW_TEXEL_BUFFER = (RHI_RESOURCE_TYPE_TEXEL_BUFFER << 1),
    RHI_RESOURCE_TYPE_COMBINED_IMAGE_SAMPLER = (RHI_RESOURCE_TYPE_RW_TEXEL_BUFFER << 1),
#endif
    RHI_RESOURCE_TYPE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIResourceType;

typedef enum ERHITextureViewUsage
{
    RHI_TVU_SRV = 0x01,
    RHI_TVU_RTV_DSV = 0x02,
    RHI_TVU_UAV = 0x04,
    RHI_TVU_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHITextureViewUsage;
typedef uint32_t ERHITextureViewUsages;

typedef enum ERHITextureViewAspect
{
    RHI_TVA_COLOR = 0x01,
    RHI_TVA_DEPTH = 0x02,
    RHI_TVA_STENCIL = 0x04,
    RHI_TVA_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHITextureViewAspect;
typedef uint32_t ERHITextureViewAspects;

// Same value as Vulkan Enumeration Bits.
typedef enum ERHIShaderStage
{
    RHI_SHADER_STAGE_NONE = 0,
    RHI_SHADER_STAGE_VERT = 0X00000001,
    RHI_SHADER_STAGE_TESC = 0X00000002,
    RHI_SHADER_STAGE_TESE = 0X00000004,
    RHI_SHADER_STAGE_GEOM = 0X00000008,
    RHI_SHADER_STAGE_FRAG = 0X00000010,
    RHI_SHADER_STAGE_COMPUTE = 0X00000020,
    RHI_SHADER_STAGE_RAYTRACING = 0X00000040,

    RHI_SHADER_STAGE_ALL_GRAPHCIS = (uint32_t)RHI_SHADER_STAGE_VERT | (uint32_t)RHI_SHADER_STAGE_TESC | (uint32_t)RHI_SHADER_STAGE_GEOM | (uint32_t)RHI_SHADER_STAGE_FRAG,
    RHI_SHADER_STAGE_HULL = RHI_SHADER_STAGE_TESC,
    RHI_SHADER_STAGE_DOMAIN = RHI_SHADER_STAGE_TESE,
    RHI_SHADER_STAGE_COUNT = 6,
    RHI_SHADER_STAGE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIShaderStage;
typedef uint32_t ERHIShaderStages;

typedef enum ERHIShaderTarget
{
#if defined (DIRECT3D11)
    shader_target_5_0,
#endif
    shader_target_5_1,
    shader_target_6_0,
    shader_target_6_1,
    shader_target_6_2,
    shader_target_6_3,
    shader_target_6_4,
} ERHIShaderTarget;

typedef enum ERHIVertexInputRate
{
    RHI_INPUT_RATE_VERTEX = 0,
    RHI_INPUT_RATE_INSTANCE = 1,
    RHI_INPUT_RATE_COUNT,
    RHI_INPUT_RATE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIVertexInputRate;

typedef enum ERHIPrimitiveTopology
{
    RHI_PRIM_TOPO_POINT_LIST = 0,
    RHI_PRIM_TOPO_LINE_LIST,
    RHI_PRIM_TOPO_LINE_STRIP,
    RHI_PRIM_TOPO_TRIANGLE_LIST,
    RHI_PRIM_TOPO_TRIANGLE_STRIP,
    RHI_PRIM_TOPO_PATCH_LIST,
    RHI_PRIM_TOPO_COUNT,
    RHI_PRIM_TOPO_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIPrimitiveTopology;

typedef enum ERHIBlendMode
{
    RHI_BLEND_MODE_ADD = 0,
    RHI_BLEND_MODE_SUBTRACT,
    RHI_BLEND_MODE_REVERSE_SUBTRACT,
    RHI_BLEND_MODE_MIN,
    RHI_BLEND_MODE_MAX,
    RHI_BLEND_MODE_COUNT,
    RHI_BLEND_MODE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIBlendMode;

typedef enum ERHIBlendConstant
{
    RHI_BLEND_CONST_ZERO = 0,
    RHI_BLEND_CONST_ONE,
    RHI_BLEND_CONST_SRC_COLOR,
    RHI_BLEND_CONST_ONE_MINUS_SRC_COLOR,
    RHI_BLEND_CONST_DST_COLOR,
    RHI_BLEND_CONST_ONE_MINUS_DST_COLOR,
    RHI_BLEND_CONST_SRC_ALPHA,
    RHI_BLEND_CONST_ONE_MINUS_SRC_ALPHA,
    RHI_BLEND_CONST_DST_ALPHA,
    RHI_BLEND_CONST_ONE_MINUS_DST_ALPHA,
    RHI_BLEND_CONST_SRC_ALPHA_SATURATE,
    RHI_BLEND_CONST_BLEND_FACTOR,
    RHI_BLEND_CONST_ONE_MINUS_BLEND_FACTOR,
    RHI_BLEND_CONST_COUNT,
    RHI_BLEND_CONST_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIBlendConstant;

typedef enum ERHICullMode
{
    RHI_CULL_MODE_NONE = 0,
    RHI_CULL_MODE_BACK,
    RHI_CULL_MODE_FRONT,
    RHI_CLUU_MODE_BOTH,
    RHI_CULL_MODE_COUNT,
    RHI_CULL_MODE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHICullMode;

typedef enum ERHIFrontFace
{
    RHI_FRONT_FACE_COUNTER_CLOCKWISE = 0,
    RHI_FRONT_FACE_CLOCKWISE,
    RHI_FRONT_FACE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIFrontFace;

typedef enum ERHIFillMode
{
    RHI_FILL_MODE_SOLID = 0,
    RHI_FILL_MODE_WIREFRAME,
    RHI_FILL_MODE_COUNT,
    RHI_FILL_MODE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIFillMode;

typedef enum ERHICompareMode
{
    RHI_CMP_NEVER = 0,
    RHI_CMP_LESS,
    RHI_CMP_EQUAL,
    RHI_CMP_LESS_EQUAL,
    RHI_CMP_GREATER,
    RHI_CMP_NOT_EQUAL,
    RHI_CMP_GREATER_EQUAL,
    RHI_CMP_ALWAYS,
    RHI_CMP_COUNT,
    RHI_CMP_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHICompareMode;

typedef enum ERHIStencilOp
{
    RHI_STENCIL_OP_KEEP = 0,
    RHI_STENCIL_OP_ZERO,
    RHI_STENCIL_OP_REPLACE,
    RHI_STENCIL_OP_INVERT,
    RHI_STENCIL_OP_INCR,
    RHI_STENCIL_OP_DECR,
    RHI_STENCIL_OP_INCR_SAT,
    RHI_STENCIL_OP_DECR_SAT,
    RHI_STENCIL_OP_COUNT,
    RHI_STENCIL_OP_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIStencilOp;

typedef enum ERHIAddressMode
{
    RHI_ADDRESS_MODE_MIRROR = 0,
    RHI_ADDRESS_MODE_REPEAT,
    RHI_ADDRESS_MODE_CLAMP_TO_EDGE,
    RHI_ADDRESS_MODE_CLAMP_TO_BORDER,
    RHI_ADDRESS_MODE_MODE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIAddressMode;

typedef enum ERHIMipMapMode
{
    RHI_MIPMAP_MODE_NEAREST = 0,
    RHI_MIPMAP_MODE_LINEAR,
    RHI_MIPMAP_MODE_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIMipMapMode;

typedef enum ERHILoadAction
{
    RHI_LOAD_ACTION_DONT_CARE = 0,
    RHI_LOAD_ACTION_LOAD,
    RHI_LOAD_ACTION_CLEAR,
    RHI_LOAD_ACTION_COUNT,
    RHI_LOAD_ACTION_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHILoadAction;

typedef enum ERHIStoreAction
{
    RHI_STORE_ACTION_STORE = 0,
    RHI_STORE_ACTION_DISCARD,
    RHI_STORE_ACTION_COUNT,
    RHI_STORE_ACTION_MAX_ENUM_BIT = 0x7FFFFFFF
} ERHIStoreAction;

